# Generated by Django 5.2.4 on 2025-07-27 02:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('inn', models.CharField(db_index=True, max_length=20, unique=True)),
                ('legalName', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(default='Узбекистан', max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('companyGroup', models.CharField(blank=True, max_length=255, null=True)),
                ('clientStatus', models.CharField(choices=[('new', 'Новый'), ('active', 'Активный'), ('vip', 'VIP'), ('inactive', 'Неактивный')], default='new', max_length=10)),
                ('financialReporting', models.CharField(default='No', max_length=3)),
                ('revenue', models.FloatField(default=0)),
                ('revenueCurrency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD'), ('EUR', 'EUR')], default='UZS', max_length=3)),
                ('revenuePeriod', models.CharField(blank=True, max_length=20, null=True)),
                ('creditLimit', models.FloatField(default=0)),
                ('limitCurrency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD'), ('EUR', 'EUR')], default='UZS', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateField(default=django.utils.timezone.now)),
                ('insuranceAmount', models.FloatField()),
                ('insuranceAmountCurrency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD'), ('EUR', 'EUR')], default='UZS', max_length=3)),
                ('premium', models.FloatField()),
                ('netPremium', models.FloatField()),
                ('premiumCurrency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD'), ('EUR', 'EUR')], default='UZS', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('pending', 'Ожидает'), ('expired', 'Истек')], default='pending', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='api.client')),
            ],
        ),
    ]
